  Parameters:
    EnvironmentType:
      Type: String
      Default: dev
      AllowedValues:
        - dev
        - staging
        - prod
      Description: Environment type (dev, staging or prod)
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Tags:
        - Key: EnvironmentType
          Value: !Ref EnvironmentType